template = "https://github.com/giellalt/template-lang-und"
rev_id = 301
template_sha = "14c7684fb7ae87003fef7c476a4f619d2addefa7"

[replacements]
__GLOTTOLOG_ID__ = "nene1249"
__REPO__ = "lang-yrk"
__UND2C__ = "yrk"
__UNDEFINED__ = "Nenets"
__UND__ = "yrk"
