template = "https://github.com/giellalt/template-lang-und"
rev_id = 281
template_sha = "818353eecbfc8e1309992f6739dfde72a0afbec0"

[replacements]
__GLOTTOLOG_ID__ = "nene1249"
__REPO__ = "lang-yrk"
__UND2C__ = "yrk"
__UNDEFINED__ = "Nenets"
__UND__ = "yrk"
