template = "https://github.com/giellalt/template-lang-und"
rev_id = 314
template_sha = "ad51f89a72714ab21c4272c003b7692c820e2b18"

[replacements]
__GLOTTOLOG_ID__ = "nene1249"
__REPO__ = "lang-yrk"
__UND2C__ = "yrk"
__UNDEFINED__ = "Nenets"
__UND__ = "yrk"
