[package]
name = "yrk"
human_name = "Nenets"
version = "0.1.0"

# Table of speller tag -> filename to include in the bundle
# filenames depends on specific project
[spellers.yrk]
filename = "yrk-mobile.zhfst"

# Table of bundles to generated
# key is the type of bundle
# Windows speller bundle require a uuid for the installer
[bundles.speller_win]
package = "speller-yrk"
platform = "windows"
uuid = "1357CEA4-CD3F-4872-B9EE-902C9E307E85"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_macos]
pkg_id = "no.divvun.MacDivvun.yrk"
package = "speller-yrk"
platform = "macos"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_win_mso]
package = "speller-yrk-mso"
platform = "windows"
uuid = "EEC0E9D0-876A-45F3-A640-53CB4E8CFDBA"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_mobile]
package = "speller-yrk"
platform = "mobile"
repo = "https://pahkat.uit.no/main/"
